### PR TITLE
Improve API docs

### LINKED ISSUE #80: Define API response models
FastAPI requires `pydantic` models to fill in the right models for resposes in the openapi spec.

An example in the FastAPI documentation can be found here: [SQL (Relational) Databases with Peewee](https://fastapi.tiangolo.com/advanced/sql-databases-peewee/)

### LINKED ISSUE #107: Add API documentation

### LINKED ISSUE #109: Camel-case API responses

### PR DESCRIPTION
**Pull request by jdemaeyer**
- Add response model definition to OpenAPI spec
- Change all API parameters and response field names to camelCase (:warning: @ubergesundheit **breaking change**)
- Add parameter descriptions

Schemas are currently *not* auto-generated from peewee as that is quite complex and I'll investigate dropping peewee in #108.

Closes #80, closes #109, closes #107.

### CODE REVIEW

**Comment by jdemaeyer** [comment]
> (@jdemaeyer will you do us the honors?)

ain't got no merge permissions ;)

access denied

**Comment by bCyberBasti** [comment]
@jdemaeyer made you a maintainer :) hope thats fixes the permission problem 😄

**Comment by jdemaeyer** [comment]
Sweet, yep it did, thanks!

**Comment by ubergesundheit** [comment]
@bCyberBasti FYI I also removed the `Restrict who can push to matching branches` protection to master. CI checks are still in place though

**Comment by ubergesundheit** [comment]
@jdemaeyer 

Do it again

**Pull request merged**
