### PR TITLE
Calendar button

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR adds a Calendar selection button + calendar popup.

@u-rogel do you want to style this?

Related to #131 
Screen Shot 2021-01-12 at 20 50 41

### CODE REVIEW

**Comment by ubergesundheit** [comment]
ping @bCyberBasti

**Comment by bCyberBasti** [comment]
looks nice 👍  one minor thing: the close and +1 month button does not have enough spacing for mobile with fat fingers 😉

**Comment by ubergesundheit** [comment]
> looks nice +1 one minor thing: the close and +1 month button does not have enough spacing for mobile with fat fingers wink

Good catch.. I've played around with spacings in 985736b

**Comment by ubergesundheit** [comment]
Forgot to attach a screenshot ... 


Screen Shot 2021-01-19 at 18 04 55

**Review by bCyberBasti — APPROVED** [review]

**Pull request merged**
