### PR TITLE
add iframe

### PR DESCRIPTION
**Pull request by ubergesundheit**
Don't merge. For now just exploration.

### CODE REVIEW

**Comment by bCyberBasti** [comment]
Added the "real" url.. they need to change their headers to allow iFrame embedding.. will ping as soon as they resolved that

**Comment by bCyberBasti** [comment]
@ubergesundheit could you double check why the embedding does not work? i have the gut feeling that our own header are preventing the embedding? if i try the url in e.g. jsfiddle it JustWorks™️ 🤷‍♂️

**Comment by ubergesundheit** [comment]
Scripts in the iframe were not executing due to how the iframe element was configured.

Regarding web security we should definitely use [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) to lock down the page displaying iframes to mitigate changing content served under the same url as before.

Regarding the example page displayed, maybe the creators could fix:

- Requesting content from multiple origins. Apart from `bike-frontend.azurewebsites.net`, it loads from `www.die-glocke.de`. `cartodb-basemaps-a.global.ssl.fastly.net`, `fonts.googleapis.com`, `fonts.gstatic.com`, `mapio.net`, `www.radstation.de` and `www.wn.de`. IMO security would be increased drastically if everything would be served from the same domain.
- Firefox prints this error:
```
XML Parsing Error: junk after document element
Location: https://bike-frontend.azurewebsites.net/
Line Number 1, Column 398:
```

**Comment by vshaibe** [comment]
> 
> 
> Scripts in the iframe were not executing due to how the iframe element was configured.
> 
> Regarding web security we should definitely use [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) to lock down the page displaying iframes to mitigate changing content served under the same url as before.
> 
> Regarding the example page displayed, maybe the creators could fix:
> 
>     * Requesting content from multiple origins. Apart from `bike-frontend.azurewebsites.net`, it loads from `www.die-glocke.de`. `cartodb-basemaps-a.global.ssl.fastly.net`, `fonts.googleapis.com`, `fonts.gstatic.com`, `mapio.net`, `www.radstation.de` and `www.wn.de`. IMO security would be increased drastically if everything would be served from the same domain.
> 
>     * Firefox prints this error:
> 
> 
> ```
> XML Parsing Error: junk after document element
> Location: https://bike-frontend.azurewebsites.net/
> Line Number 1, Column 398:
> ```
Hi there,
I recently updated https://bike-frontend.azurewebsites.net/ site:
- XML-Error is fixed
- External dependencies reduced to one (cartodb-basemaps-a.global.ssl.fastly.net). This is open-street-map server, map module depends on it.

Is it necessary to have only local dependencies in App? Cause it takes quite a lot of effort to deploy local open-street-map server

Best regards,
Vadim Shaibe

**Comment by ubergesundheit** [comment]
Thanks!

> Is it necessary to have only local dependencies in App?

Should be fine for now.

**Comment by ubergesundheit** [comment]
So before I regard this as ready I currently see these things to do/change:

- [ ] Enable interaction with iFrame but also allowing to change the slide
- [ ] Set CSP `<meta...` tag to try to make it at least a little secure

**Comment by ubergesundheit** [comment]
> Set CSP <meta... tag to try to make it at least a little secure

This is parly done but needs to be made dynamic. I sense we will host images always from the same domain & iframes won't come from the api either. So I vote for keeping the configuration static.

**Comment by ubergesundheit** [comment]
@bCyberBasti lets get this into master :tada:

**Comment by bCyberBasti** [comment]
@ubergesundheit did you try to find a solution for the "interaction problem" ? Right now the slider simply slides away, even if I just clicked on something in the iframe..

**Comment by ubergesundheit** [comment]
Did not check. I would try to tackle #175 and #176 next.

For keeping the history (and myself) sane I would like to merge this into master so this does not need any more manual git conflict resolutions.

**Review by bCyberBasti — APPROVED** [review]
ready to merge

**Pull request merged**
