### PR TITLE
Add all font weights

### PR DESCRIPTION
**Pull request by ubergesundheit**
Related to #220 

This PR adds all font weights. I only have a Windows PC available, this solved at least the glitches @simsal0r reported.

I'll go ahead and merge without reviews because this does not change any functionality. Please check https://staging.muenster-jetzt.de if this resolves the visual font glitches

### CODE REVIEW

**Comment by ubergesundheit** [comment]
btw at least in firefox, it downloads only the fonts it needs, not everything...

**Comment by bCyberBasti** [comment]
Unfortunately it did not solve the problem on mac

in addition to that Chrome/Brave seems to be not that clever and downloads all of the fonts multiple times:
image

**Comment by simsal0r** [comment]
The visual glitches that I reported are not present anymore on Firefox, Windows.

**Comment by ubergesundheit** [comment]
> in addition to that Chrome/Brave seems to be not that clever and downloads all of the fonts multiple times

If you look closely it only loads `regular`, `300`, `500`, and `700`. The file defines more than these four weights.. So this seem to work.

Have you enabled the `Disable Cache` checkbox in your network tab?

**Comment by bCyberBasti** [comment]
> Have you enabled the Disable Cache checkbox in your network tab?

Yes but i reloaded the page multiple times and did preserve the log 🤦  so this is also solved 😄

**Pull request merged**
