### PR TITLE
add config for production deployment

### PR DESCRIPTION
**Pull request by bCyberBasti**

### CODE REVIEW

**Review by ubergesundheit — APPROVED** [review]
LGTM

Don't forget to set up branch protection for the `production` branch.

**Comment by bCyberBasti** [comment]
> Don't forget to set up branch protection for the `production` branch.

Could you double check my config: https://github.com/codeformuenster/muenster-jetzt/settings/branch_protection_rules/17336482

**Comment by ubergesundheit** [comment]
> Could you double check my config: https://github.com/codeformuenster/muenster-jetzt/settings/branch_protection_rules/17336482

I think its missing `Include administrators`

**Comment by bCyberBasti** [comment]
> > Could you double check my config: https://github.com/codeformuenster/muenster-jetzt/settings/branch_protection_rules/17336482
> 
> I think its missing `Include administrators`

My idea was: if we have "tested" it in staging i would be able to simply deploy it on my own without another check from someone else 😉  does that make any sense or should we stick to reviews for everything?

**Comment by ubergesundheit** [comment]
Yeah you're right. At some point we should think about requiring approvals for merges into master.

**Pull request merged**
