### PR TITLE
scrapy raises exception on error status code

### PR DESCRIPTION
**Pull request by ebleb**
scrapy now raises an exception when the request returns an error status code as requested in issue #188

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Looks nice! Would it be possible to define the `custom_settings` and `handle_error` outside of the scraper files to reuse them?

**Comment by ubergesundheit** [comment]
Thanks for quickly reacting!

@bCyberBasti lets think about implications of running these changes on the server. As I understand, right now, scrapers don't fail on incorrect http status errors. Will this tear down all scraping once an error is encountered or will it just skip to the next scraper?

**Comment by ebleb** [comment]
I'm not sure if that answers your question, but the changes made lead to scrapy only closing the spider that encountered the error.

**Comment by ubergesundheit** [comment]
Just a quick heads up: I'm planning to merge #268 before this, If you don't mind to be patient, propbably your PR needs some changes then.

**Comment by ubergesundheit** [comment]
@ebleb would you be so kind to adapt your PR for the changed backend?

**Comment by ebleb** [comment]
The scrapers should now work with the new backend. The build fails, probably because I don't have access to the docker login secrets as I'm not a collaborator.
> Anyone with collaborator access to [a] repository can use [...] secrets for Actions.

**Comment by ubergesundheit** [comment]
Thanks :)

**Pull request merged**
