### PR TITLE
fixes occurrences of unused self

### PR DESCRIPTION
**Pull request by ebleb**
resolves the issue #163.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
@jdemaeyer any thoughts or comments to this?

**Comment by jdemaeyer** [comment]
(The following will read a little harsh, but rest assured all my anger is pointed at DeepSource and not at you guys ;))

My personal opinion is that DeepSource is way too sensitive and most of the issues it opens should be ignored (and I find it an atrocity that we cannot disable certain "error" types like PYL-R0201 project-wide). I mean: "so that Python does not have to instantiate a bound method for every instance of this class thereby saving memory and computation" (from #163), wtf?! This may be relevant in a very special edge case where we create and destroy thousands of instances of a certain class per second _and_ every microsecond is critical to our application, but should certainly not be a "code smell" check for every basic project (and IMHO following DeepSource here and cluttering the code with static methods everywhere is the much worse code smell of premature optimization). Here are the "computation savings" that the DeepSource solution gets us:

```python

In [1]: class X:
   ...: 
   ...:     def blah(self):
   ...:         return True
   ...: 

In [2]: class Y:
   ...: 
   ...:     @staticmethod
   ...:     def blah():
   ...:         return True
   ...: 

In [3]: %timeit X()
80.1 ns ± 0.266 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)

In [4]: %timeit Y()
78.1 ns ± 0.416 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

A grand total of saving six *nano*seconds per crawl, at the cost of making our code harder to read, departing from the interface contract that Scrapy has set for us, and worst of all making @ebleb spend his precious developer time on absolute non-issues.

My two cents are that the right way to resolve #163 is to disable DeepSource for our Python codebase entirely (because we absolutely shouldn't trust developers who consider "No use of `self`" a code smell for every basic project). A "meh" solution is to add "ignore PYL-R0201" markers everywhere it complains.

That being said, it seems that merging this PR will at least not break scraping, although I haven't checked.

**Comment by ubergesundheit** [comment]
Whoa huge thanks for explaining this so well and even taking your time to benchmark the different implementations.

IMO you're right in the sense that deepsource should be disabled. I'll go forward and do this right now. Once we notice performance issues we can spend time for this kind of optimizations

**Comment by ebleb** [comment]
Thank you for the thorough explanation. Should I revert the static method I added in #308 back to a regular method?

**Comment by jdemaeyer** [comment]
Sure, if you find a spare minute, otherwise it probably also doesn't hurt too much if it keeps sitting there ;)

**Pull request closed without merging**
