### PR TITLE
apply black

### PR DESCRIPTION
**Pull request by ThorbenJensen**
simply autoformatting with `black`.
if there is a preference for `'` over `"`, feel free to configure black in `pyproject.toml` :-)

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Once everyone is happy, this should also be enforced through CI. There is already checking happening through tox or something

**Review by jdemaeyer — CHANGES_REQUESTED** [review]
Could you replace our call to `flake8` with the proper call to `black` in our `tox.ini` (and replace the dependency)? Otherwise LGTM!

**Comment by ThorbenJensen** [comment]
@ubergesundheit, enforcing the format check now.

@jdemaeyer, how about checking both `black` and `flake8`, as is being done now?

**Comment by jdemaeyer** [comment]
> @jdemaeyer, how about checking both `black` and `flake8`, as is being done now?

Hm, isn't `black` always producing PEP8 compliant formatting (and any test for "black-formatted-ness" like `black --check` is therefore also a test for PEP8 compliancy)? What's the point of running the additional PEP8 check via `flake8` then?

**Comment by ThorbenJensen** [comment]
> What's the point of running the additional PEP8 check via `flake8` then?

`black` and `flake8` are a bit different in what they cover.
flake8 cares about more "subtleties", for instance unused imports; so with an unused "import xyz", flake8 fails, but black is fine.

**Comment by jdemaeyer** [comment]
Ah, I had somehow assumed black would auto-correct these as well. We should definitely keep `flake8` then. Changes LGTM, feel free to merge

**Review by jdemaeyer — APPROVED** [review]

**Pull request merged**
